// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npesnjmygznqqadgkcfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZXNuam15Z3pucXFhZGdrY2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Nzk3MTIsImV4cCI6MjA3MjU1NTcxMn0.4Ol4dwzsASb6cm7xlZClB8aM2CkFizMzrI5SxSYVeBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});